In [1]:
import requests
import json
import pandas as pd
import time
from datetime import datetime

url = "https://community-open-weather-map.p.rapidapi.com/weather"

querystring = {"q":"Denver,usa","lat":"0","lon":"0","id":"2172797","lang":"null","units":"imperial"}

headers = {
	"X-RapidAPI-Host": "community-open-weather-map.p.rapidapi.com",
	"X-RapidAPI-Key": "9d95859ef4msh1bff28eb9a10263p1e0e90jsnaf12afa0b707"
}

counter = 0

# first time through
response = requests.request("GET", url, headers=headers, params=querystring)

# print(response.text)

data = json.loads(response.text)
df = pd.json_normalize(data)

# datetime object containing current date and time
now = datetime.now()
# dd/mm/YY H:M:S
dt_string = now.strftime("%m/%d/%Y %H:%M:%S")
# print(dt_string)

df.insert(0, 'Date', dt_string)

while counter < 19:
    time.sleep(15)
    response = requests.request("GET", url, headers=headers, params=querystring)

    # print(response.text)

    data = json.loads(response.text)
    clean_up = pd.json_normalize(data)
    
    # datetime object containing current date and time
    now = datetime.now()
    # dd/mm/YY H:M:S
    dt_string = now.strftime("%m/%d/%Y %H:%M:%S")
    # print(dt_string)

    clean_up.insert(0, 'Date', dt_string)
    
    df = df.append(clean_up, ignore_index = True)
    
    counter = counter + 1
    

dropcols = ['weather', 'base', 'visibility', 'dt', 'timezone', 'id', 'cod', 'main.pressure', 'main.humidity',
            'wind.deg', 'wind.gust', 'clouds.all', 'sys.type', 'sys.id', 'sys.sunrise','sys.sunset', 
            'main.feels_like', 'sys.country']
df.drop(dropcols, axis=1, inplace=True)

rename_cols = {"name":"City", "coord.lon":"Longitude", "coord.lat":"Latitude", "main.temp":"Temp",
               "main.temp_min":"Low Temp", "main.temp_max":"High Temp", "wind.speed":"Wind Speed"}
df.rename(columns=rename_cols, inplace=True)

In [2]:
df

,Date,City,Longitude,Latitude,Temp,Low Temp,High Temp,Wind Speed
0,05/12/2022 10:29:10,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
1,05/12/2022 10:29:25,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
2,05/12/2022 10:29:40,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
3,05/12/2022 10:29:55,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
4,05/12/2022 10:30:10,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
5,05/12/2022 10:30:26,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
6,05/12/2022 10:30:41,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
7,05/12/2022 10:30:56,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
8,05/12/2022 10:31:11,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
9,05/12/2022 10:31:26,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
10,05/12/2022 10:31:42,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
11,05/12/2022 10:31:57,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
12,05/12/2022 10:32:12,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
13,05/12/2022 10:32:27,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
14,05/12/2022 10:32:42,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
15,05/12/2022 10:32:58,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
16,05/12/2022 10:33:13,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
17,05/12/2022 10:33:28,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
18,05/12/2022 10:33:43,Denver,-104.9847,39.7392,60.75,52.7,70.47,3
19,05/12/2022 10:33:58,Denver,-104.9847,39.7392,60.75,52.7,70.47,3

In [4]:
df.to_csv("C:/Users/rpwoo/Desktop/Second Year Spring (2022)/DS 3002/DS-3002-01-main/FINAL PROJECT/streamingdata.csv")